from collections import defaultdict


def empty_annotations():
    return {
        "counts": {
            "classes": defaultdict(int),
            "slots": defaultdict(int),
            "pairs": defaultdict(lambda: defaultdict(lambda: defaultdict(int))),
        },
        "examples": {
            "classes": defaultdict(str),
            "pairs": defaultdict(lambda: defaultdict(lambda: defaultdict(dict))),
        },
    }


def linkml_schema(graph_name, graph_title, graph_description):
    output_schema = {
        "id": "okns:" + graph_name,
        # version
        "imports": set([]),
        # license
        "prefixes": {
            "okns": "https://purl.org/okn/schema/",
            "okn": "https://purl.org/okn/",
        },
        # emit_prefixes
        # default_curi_maps
        "default_prefix": "okns",
        # default_range
        # subsets
        "types": defaultdict(linkml_type),
        # enums
        "slots": defaultdict(linkml_slot),
        "classes": defaultdict(linkml_class),
        # metamodel_version
        # source_file
        # source_file_date
        # source_file_size
        # generation_date
        # slot_names_unique
        # settings
        # bindings
        "name": graph_name,
        # id_prefixes
        # id_prefixes_are_closed
        # definition_uri
        # local_names
        # conforms_to
        # implements
        # instantiates
        # extensions
        "annotations": empty_annotations(),
        "description": graph_description or "",
        # alt_descriptions
        "title": graph_title or "",
        # deprecated
        # todos
        # notes
        # comments
        # examples
        # in_subset
        # from_schema
        # imported_from
        # source
        # in_language
        # see_also
        # deprecated_element_has_exact_replacement
        # deprecated_element_has_possible_replacement
        # aliases
        # structured_aliases
        # mappings
        # exact_mappings
        # close_mappings
        # related_mappings
        # narrow_mappings
        # broad_mappings
        # created_by
        # contributors
        # created_on
        # last_updated_on
        # modified_by
        # status
        # rank
        # categories
        # keywords
    }
    return output_schema


def linkml_type():
    return {
        "typeof": "string",
        # base
        "uri": "",
        # repr
        # union_of
        # pattern
        # structured_pattern
        # unit
        # implicit_prefix
        # equals_string
        # equals_string_in
        # equals_number
        # minimum_value
        # maximum_value
        # none_of
        # exactly_one_of
        # any_of
        # all_of
        "name": "",
        # id_prefixes
        # id_prefixes_are_closed
        # definition_uri
        # local_names
        # conforms_to
        # implements
        # instantiates
        # extensions
        # annotations
        # description
        # alt_descriptions
        # title
        # deprecated
        # todos
        "notes": [],
        # comments
        # examples
        # in_subset
        # from_schema
        # imported_from
        # source
        # in_language
        # see_also
        # deprecated_element_has_exact_replacement
        # deprecated_element_has_possible_replacement
        # aliases
        # structured_aliases
        # mappings
        # exact_mappings
        # close_mappings
        # related_mappings
        # narrow_mappings
        # broad_mappings
        # created_by
        # contributors
        # created_on
        # last_updated_on
        # modified_by
        # status
        # rank
        # categories
        # keywords
    }


def linkml_class():
    return {
        "slots": set(),
        # slot_usage
        # attributes
        # class_uri
        # subclass_of
        # union_of
        # defining_slots
        # tree_root
        # unique_keys
        # rules
        # classification_rules
        # slot_names_unique
        # represents_relationship
        # disjoint_with
        # children_are_mutually_disjoint
        # any_of
        # exactly_one_of
        # none_of
        # all_of
        # slot_conditions
        # is_a
        # abstract
        # mixin
        # mixins
        # apply_to
        # values_from
        # string_serialization
        "name": "",
        # id_prefixes
        # id_prefixes_are_closed
        # definition_uri
        # local_names
        # conforms_to
        # implements
        # instantiates
        # extensions
        # annotations
        # description
        # alt_descriptions
        # title
        # deprecated
        # todos
        "notes": [],
        "comments": defaultdict(set),
        # examples
        # in_subset
        # from_schema
        # imported_from
        # source
        # in_language
        # see_also
        # deprecated_element_has_exact_replacement
        # deprecated_element_has_possible_replacement
        # aliases
        # structured_aliases
        # mappings
        # exact_mappings
        # close_mappings
        # related_mappings
        # narrow_mappings
        # broad_mappings
        # created_by
        # contributors
        # created_on
        # last_updated_on
        # modified_by
        # status
        # rank
        # categories
        # keywords
    }


def linkml_slot():
    return {
        # singular_name
        # domain
        # slot_uri
        # array
        # inherited
        # readonly
        # ifabsent
        # list_elements_unique
        # list_elements_ordered
        # shared
        # key
        # identifier
        # designates_type
        # alias
        # owner
        # domain_of
        # subproperty_of
        # symmetric
        # reflexive
        # locally_reflexive
        # irreflexive
        # asymmetric
        # transitive
        # inverse
        # is_class_field
        # transitive_form_of
        # reflexive_transitive_form_of
        # role
        # is_usage_slot
        # usage_slot_name
        # relational_role
        # slot_group
        # is_grouping_slot
        # path_rule
        # disjoint_with
        # children_are_mutually_disjoint
        "union_of": set(),
        # type_mappings
        "range": "Any",
        # range_expression
        # enum_range
        # bindings
        # required
        # recommended
        # multivalued
        # inlined
        # inlined_as_list
        # minimum_value
        # maximum_value
        # pattern
        # structured_pattern
        # unit
        # implicit_prefix
        # value_presence
        # equals_string
        # equals_string_in
        # equals_number
        # equals_expression
        # exact_cardinality
        # minimum_cardinality
        # maximum_cardinality
        # has_member
        # all_members
        # none_of
        # exactly_one_of
        "any_of": set(),
        # all_of
        # is_a
        # abstract
        # mixin
        # mixins
        # apply_to
        # values_from
        # string_serialization
        # name
        # id_prefixes
        # id_prefixes_are_closed
        # definition_uri
        # local_names
        # conforms_to
        # implements
        # instantiates
        # extensions
        # annotations
        # description
        # alt_descriptions
        # title
        # deprecated
        # todos
        # notes
        "comments": defaultdict(set),
        # examples
        # in_subset
        # from_schema
        # imported_from
        # source
        # in_language
        # see_also
        # deprecated_element_has_exact_replacement
        # deprecated_element_has_possible_replacement
        # aliases
        # structured_aliases
        # mappings
        # exact_mappings
        # close_mappings
        # related_mappings
        # narrow_mappings
        # broad_mappings
        # created_by
        # contributors
        # created_on
        # last_updated_on
        # modified_by
        # status
        # rank
        # categories
        # keywords
    }
